version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        hostname: elasticsearch
        ports:
            - "9200:9200"
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    redis:
        image: redis:6.2.6
        ports:
            - "6379:6379"
    worker:
        build: .
        command: bundle exec rake environment resque:work QUEUE=*
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
        environment:
            REDIS_URL: redis://redis:6379
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
    app: 
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - db
            - redis
            - elasticsearch
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_URL: redis://redis:6379
            ELASTICSEARCH_URL: docker.elastic.co/elasticsearch/elasticsearch:7.5.2://elasticsearch:9200